<?php

namespace GsbFrais\ConnexionBundle\Repository;

/**
 * VisiteurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VisiteurRepository extends \Doctrine\ORM\EntityRepository
{

    public function seConnecter ($login, $mdp){
        $queryBuilder = $this->_em->createQueryBuilder()
                    ->select('v') //v l'alias de visiteur
                    ->from( $this->_entityName, 'v') // FROM Visteur
                    ->where("v.login = :login") // comparaison login
                    ->andWhere("v.mdp = :mdp") //comparaison mdp
                    ->setParameter('login', $login) // remplace :login dans la comparaison
                    ->setParameter('mdp', $mdp) // remplace :mdp dans la comparaison
                    ->getQuery()
                    ->getResult();

        return $queryBuilder;
    }

    public function getVisiteur ($idVis){
        $queryBuilder = $this->_em->createQueryBuilder()
            ->select('v') //v l'alias de visiteur
            ->from( $this->_entityName, 'v') // FROM Visteur
            ->where("v.id = :id") // comparaison id
            ->setParameter('id', $idVis) // remplace :login dans la comparaison
            ->getQuery()
            ->getResult();

        return $queryBuilder;
    }

}
