<?php

namespace GsbFrais\ProfilBundle\Repository;

/**
 * EtatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EtatRepository extends \Doctrine\ORM\EntityRepository
{

    public function getEtat($idEtat){
        $queryBuilder = $this->_em->createQueryBuilder()
            ->select('e')
            ->from($this->_entityName, 'e')
            ->where('e.id = :id')
            ->setParameter('id', $idEtat)
            ->getQuery()
            ->getResult();

        return $queryBuilder;
    }

}
