<?php

namespace GsbFrais\ProfilBundle\Repository;

/**
 * LigneFraisHorsForfaitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LigneFraisHorsForfaitRepository extends \Doctrine\ORM\EntityRepository
{

    public function getFraisHorsForfaitMois($idFicheFrais){
        //création de ma requête en indiquant l'alias utilisé l'entité "LigneFraisHorsForfait"
        $maRequete = $this->createQueryBuilder('lfhf')
            //from LigneFraisHorsForfait lfhf inner join FraisForfait ff ON lfhf.idFicheFrais = ff.id
            //(Grace au manyToOne)
            //WHERE ff.id = $idFicheFrais
            ->join('lfhf.idFicheFrais', 'ff', 'WITH', 'ff.id = :idFiche')
            //On veut aussi récupérer tous les éléments de fiche frais en plus des attributs de la ligne frais hors forfait
            ->addSelect('ff')
            //:idFiche = $idFicheFrais
            ->setParameter('idFiche', $idFicheFrais)
            ->orderBy('lfhf.date', 'DESC')
            //Envoie requete
            ->getQuery()
            //Recup resultat sous forme d'objet
            ->getResult();

        //Retour de la réponse
        return $maRequete;
    }

    public function getLeFraisHorsForfaitMois($idHorsForfait){
        //création de ma requête en indiquant l'alias utilisé l'entité "LigneFraisHorsForfait"
        $maRequete = $this->createQueryBuilder('lfhf')
            ->join('lfhf.idFicheFrais', 'ff')
            ->addSelect('ff')
            ->where('lfhf.id = :id')
            ->setParameter('id', $idHorsForfait)
            ->orderBy('lfhf.date', 'DESC')
            //Envoie requete
            ->getQuery()
            //Recup resultat sous forme d'objet
            ->getResult();

        //Retour de la réponse
        return $maRequete;
    }

}
