<?php

namespace GsbFrais\ProfilBundle\Repository;

/**
 * LigneFraisForfaitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LigneFraisForfaitRepository extends \Doctrine\ORM\EntityRepository
{

    public function getFraisForfaitMois($idFicheFrais){
        $queryBuilder = $this->createQueryBuilder('lff')
            //->select()
                //from LigneFraisForfait lff inner join FicheFrais ff ON lff.idFicheFrais = ff.id
                //WHERE ff.id = $idFicheFrais
            ->join('lff.idFicheFrais', 'ff', 'WITH', 'ff.id = :idFiche')
                //from LigneFraisForfait lff inner join FraisForfait ffo ON lff.idFraisForfait = ffo.id
            ->join('lff.idFraisForfait', 'ffo')
            ->addSelect('ff')
            ->addSelect('ffo')
            //->where('lff.idFicheFrais = :idFiche')
            ->setParameter('idFiche', $idFicheFrais)
            ->getQuery()
            ->getResult();

        return $queryBuilder;
    }

}
