<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCjfovy5\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCjfovy5/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerCjfovy5.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerCjfovy5\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerCjfovy5\appProdProjectContainer(array(
    'container.build_hash' => 'Cjfovy5',
    'container.build_id' => 'd3c4d5a3',
    'container.build_time' => 1525460223,
));
