gsb_frais_connexion:
    path:     /connexion
    defaults: { _controller: GsbFraisConnexionBundle:Connexion:register }

gsb_frais_edit_user:
    path:     /editU
    defaults: { _controller: GsbFraisConnexionBundle:GestionCompte:editerUser }

gsb_frais_edit_mdp:
    path:     /editMdp
    defaults: { _controller: GsbFraisConnexionBundle:GestionMdp:editerMdp }

