<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container4kl3u6l\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container4kl3u6l/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container4kl3u6l.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\Container4kl3u6l\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \Container4kl3u6l\appDevDebugProjectContainer(array(
    'container.build_hash' => '4kl3u6l',
    'container.build_id' => 'a8863948',
    'container.build_time' => 1524239435,
));
